#!/bin/bash


lista=("Doki Doki Literature Club (Chibi Version)" "Natsuki (Doki Doki Literature Club)" "Yuri (Doki Doki Literature Club)" "Monika (Doki Doki Literature Club)" "Sayori (Doki Doki Literature Club)")


item_aleatorio=$(printf "%s\n" "${lista[@]}" | shuf -n 1)

echo "O item escolhido aleatoriamente é: $item_aleatorio"
cd "$item_aleatorio"
chmod +x install.sh
sh install.sh
exec bash
